# Generated by Django 3.0 on 2020-08-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doner',
        ),
    ]
