# Generated by Django 3.0.7 on 2020-08-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doner', to='form.Doner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='form.Doner')),
            ],
        ),
    ]
