# Generated by Django 3.0 on 2020-08-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20200818_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='case',
            field=models.BooleanField(default='', null=True),
        ),
    ]
