# Generated by Django 3.0 on 2020-08-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20200818_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='case',
            field=models.BooleanField(default='UnKnown', null=True),
        ),
    ]
