# Generated by Django 3.0 on 2020-08-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20200818_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='case',
            field=models.BooleanField(null=True),
        ),
    ]
